workflows:
  android-debug:
    name: Android Debug Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "org.libsdl.app"
    cache:
      cache_paths:
        - $CM_BUILD_DIR/.gradle
        - $CM_BUILD_DIR/app/build
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Clone RavEngine
        script: |
          rm -rf to-build/sdl3-sample
          git clone --depth 1 https://github.com/RavEngine/RavEngine.git to-build/mygame/RavEngine
      - name: Build Android APK
        script: |
          cd app
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
